stages:
  - compile
  - test
  - build
  - image-build
  - code_quality
  - artifacts
  - deploy

compile:
  stage: compile
  tags:
  - allinone
  script:
    - mvn compile

test:
  stage: test
  tags:
  - allinone
  script:
    - mvn test

build:
  stage: build
  tags:
  - allinone
  script:
    - mvn package -Dmaven.test.skip=true
  artifacts:
   paths:
   - target/*.war

docker:
  stage: image-build
  tags:
  - allinone
  script:
    - ls
    - docker login --username=anjreddy --password=Adiyog!@112
    - docker build -t anjreddy/wipro:latest .
    - docker push anjreddy/wipro:latest


sonar:
  stage: code_quality
  tags:
  - allinone
  script:
    - mvn sonar:sonar -Dsonar.host.url=http://34.229.119.25:9000 -Dsonar.login=37e516b7aa7cbebcdf761996af4fd158a7f58c97

#nexus:
  #stage: artifacts
  #tags:
  #- allinone
  #script:
   #- mvn deploy


deploy-prod:
  stage: deploy
  tags:
  - k8
  only:
    - master
  script: 
    - pwd
    - kubectl apply -f Deployment.yml
  

   
    
