stages:
  - compile
  - test
  - build
  - image-build
  - code_quality
  - artifacts
  - deploy

include:
   - local: /config/compile.yml
   - local: /config/test.yml
   - local: /config/build.yml
   - local: /config/image-build.yml
   - local: /config/code_quality.yml
   - local: /config/artifacts.yml
   - local: /config/deploy.yml
   
    
