apiVersion: v1
kind: Service
metadata:
  name: java-service
  labels:
    app: java-service
spec:
  type: LoadBalancer
  ports:
  - port: 90
    targetport: 9090
  selector:
    app: java
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java
        image: anjreddy/wipro:latest
        
