apiVersion: v1
kind: Service
metadata:
  name: wipro-serive
  labels:
    app: wipro-serive
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: wipro
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wipro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wipro
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: wipro
    spec:
      containers:
      - name: wipro
        image: anjreddy/wipro:latest
        
