docker:
  stage: image-build
  tags:
  - minikube
  script:
    - ls
    - docker login --username=$dockeruser --password=$dockerpassword
    - docker build -t anjreddy/wipro:$version .
    - docker push anjreddy/wipro:latest
